Feat/internationlisation
InvincibleZeal/billbook pull request #63
Opened 2021-08-19 10:18 UTC by gautism1

2021-08-20 03:09 UTC, smilegupta reviewed
Looks good to me from functionality wise.

One suggestions from Design Perspective:
Make the button size small of english and espnola and align them on right side. It will look more good.

2021-08-20 05:53 UTC, rparsh commented
@gautism1 Move the language buttons inside sidebar(bottom) [hide from mobile for now]

2021-08-20 10:29 UTC, smilegupta approved these changes

2021-08-20 14:37 UTC, rparsh commented
@gautism1 default language is english but UI render French as default

2021-08-20 17:16 UTC, gautism1 commented on src/i18n/wrapper.js
> +        if (newlocale === "en-US") {
Sir the default is English and it renders English as default  ,also i change the newlocale condition to .include("en-")
Thanks,

2021-08-22 12:40 UTC, gautism1 commented
Resolves conflicts  and merged internationalisation and data-dynamic branches

2021-08-22 12:45 UTC, rparsh commented
@gautism1 please revert data dynamic branch merge ...that branch is not merged to master you cannot merge it directly

2021-08-22 12:45 UTC, rparsh requested changes
Revert dtaa dynamic branch

2021-08-23 06:27 UTC, merged